#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix/mesg || :

if [ ! -L /etc/init.d/kronometrix.mesg ]; then
    ln -s /opt/kronometrix/mesg/etc/kronometrix.mesg /etc/init.d/kronometrix.mesg || :
fi

# link here kronometrix.mesg
update-rc.d kronometrix.mesg start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix/mesg/logs ]; then
    chown -R krmx:krmx /opt/kronometrix/mesg/logs || :
fi

/etc/init.d/kronometrix.mesg start >/dev/null 2>&1 || :
