#!/bin/sh

update-rc.d -f kronometrix.mesg remove >/dev/null 2>&1 || : 

# uinstall
if [ -L /etc/init.d/kronometrix.mesg ]; then
    /etc/init.d/kronometrix.mesg stop >/dev/null 2>&1 || :
    rm -f /etc/init.d/kronometrix.mesg || :
fi
